os:
  - osx
#  - linux
cache:
  directories:
    - qt-everywhere-opensource-src-4.8.7
sudo: required
services:
  - docker
before_install:
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then ./before_install-osx.sh ; else ./before_install-linux.sh ; fi
script:
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then cd qt-everywhere-opensource-src-4.8.7; make -j4 sub-tools-bootstrap-make_default-ordered sub-moc-make_default-ordered sub-rcc-make_default-ordered sub-uic-make_default-ordered sub-corelib-make_default-ordered sub-xml-make_default-ordered sub-network-make_default-ordered sub-sql-make_default-ordered sub-testlib-make_default-ordered sub-gui-make_default-ordered sub-qt3support-make_default-ordered ; fi
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then cd qt-everywhere-opensource-src-4.8.7; make -j4 sub-uic3-make_default-ordered sub-opengl-make_default-ordered sub-xmlpatterns-make_default-ordered sub-multimedia-make_default-ordered sub-svg-make_default-ordered sub-script-make_default-ordered sub-declarative-make_default-ordered sub-webkit-make_default-ordered sub-scripttools-make_default-ordered sub-plugins-make_default-ordered sub-imports-make_default-ordered sub-tools-make_default-ordered sub-translations-make_default-ordered ; fi
deploy:
  provider: releases
  api_key:
    secure: SQXk7lgMBhI8dlpE5+xj54Tl2VMS0t3TJpJnLEgm0SBeenX3S7vmMKBaWbA1qy8zA4h9LWBXxPgy4FKL+9qLOl5cnyJghwlWxoFplUvN2PcDwtnOKcRjvGawFktKhecXTZPwUFjG8AE32jJqY+Ps+1pEgg44qUI7EoWYcPMmItWYHjeMBFfF7+MdzfHxQR7DykFr3QmDnWaTf6T/ojLE3muHBvOI0fVzhFpb0Pd1uWaG1DNtUL2/ALNFbjLKPMjlNKaozgyxUcNxSyRtFjGDlWuqr89snMDIHexG7J3d/UQtfwFg7l55XpZ/UfHCB8NwR7m7n3QYPqaMnybDIFRp8hxwcBijLsWtXy1AHW4p08hxcbDoz2jU84DtRXI6cT3zrhQeWplwS0+dkRpt7CF5SpEIzDRtabbBC5geR4Q6GFdm97fab6gFwKGJbmfcX1DTRAmpuIA0kqHASAHqI9qY0Een3B0GyeO0Ix5CHjmgVZNwY6mfx3OrDaISb7mTiwYjgeo5FKkOTKcEKYSXU1FXB/yzarvistG+lowQ4VAq/alG6sqO/SoHnQyiEw/13LjTTciWYIarP88xFtGC7/Y81k6jo7jzpnJMLRp9P6YOaJ8U5/DDQOGC2GprbqkCIAkL9NOB2bb8E2D4eYDLB7FWhBjWKbRRx7JmPW+9x6viJ5Y=
  file:
    - electrum-dash/dist/Electrum-DASH-2.6.4.tar.gz
    - electrum-dash/dist/electrum-setup.exe
  on:
    repo: akhavr/electrum-dash-release
    all_branches: true