os:
  - osx
#  - linux
sudo: required
services:
  - docker
before_install:
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
    brew update
    wget https://download.qt.io/official_releases/qt/4.8/4.8.7/qt-everywhere-opensource-src-4.8.7.tar.gz
    gunzip qt-everywhere-opensource-src-4.8.7.tar.gz
    tar -xf qt-everywhere-opensource-src-4.8.7.tar
    cd qt-everywhere-opensource-src-4.8.7
    # Patch is needed as https://codereview.qt-project.org/#/c/157137/
    cat > patchset1.patch << EOF
index 4aa0668..63b646d 100644 (file)
--- a/src/gui/painting/qpaintengine_mac.cpp
+++ b/src/gui/painting/qpaintengine_mac.cpp
@@ -340,13 +340,7 @@ CGColorSpaceRef QCoreGraphicsPaintEngine::macDisplayColorSpace(const QWidget *wi
     }
 
     // Get the color space from the display profile.
-    CGColorSpaceRef colorSpace = 0;
-    CMProfileRef displayProfile = 0;
-    CMError err = CMGetProfileByAVID((CMDisplayIDType)displayID, &displayProfile);
-    if (err == noErr) {
-        colorSpace = CGColorSpaceCreateWithPlatformColorSpace(displayProfile);
-        CMCloseProfile(displayProfile);
-    }
+    CGColorSpaceRef colorSpace = CGDisplayCopyColorSpace(displayID);
 
     // Fallback: use generic DeviceRGB
     if (colorSpace == 0)
EOF
    patch -p1 <patchset1.patch
    ./configure -prefix $HOME/virtualenv -release -opensource -confirm-license -nomake examples -nomake demos -qt-zlib -qt-libjpeg -qt-libpng -qt-libmng -qt-libtiff
  else ./before_install-linux.sh ; fi
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
    cd qt-everywhere-opensource-src-4.8.7
    make -j4
  fi
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
    cd qt-everywhere-opensource-src-4.8.7
    make install
  fi
  
script:
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then ./travis-build-osx.sh ; else ./travis-build-linux.sh ; fi
deploy:
  provider: releases
  api_key:
    secure: SQXk7lgMBhI8dlpE5+xj54Tl2VMS0t3TJpJnLEgm0SBeenX3S7vmMKBaWbA1qy8zA4h9LWBXxPgy4FKL+9qLOl5cnyJghwlWxoFplUvN2PcDwtnOKcRjvGawFktKhecXTZPwUFjG8AE32jJqY+Ps+1pEgg44qUI7EoWYcPMmItWYHjeMBFfF7+MdzfHxQR7DykFr3QmDnWaTf6T/ojLE3muHBvOI0fVzhFpb0Pd1uWaG1DNtUL2/ALNFbjLKPMjlNKaozgyxUcNxSyRtFjGDlWuqr89snMDIHexG7J3d/UQtfwFg7l55XpZ/UfHCB8NwR7m7n3QYPqaMnybDIFRp8hxwcBijLsWtXy1AHW4p08hxcbDoz2jU84DtRXI6cT3zrhQeWplwS0+dkRpt7CF5SpEIzDRtabbBC5geR4Q6GFdm97fab6gFwKGJbmfcX1DTRAmpuIA0kqHASAHqI9qY0Een3B0GyeO0Ix5CHjmgVZNwY6mfx3OrDaISb7mTiwYjgeo5FKkOTKcEKYSXU1FXB/yzarvistG+lowQ4VAq/alG6sqO/SoHnQyiEw/13LjTTciWYIarP88xFtGC7/Y81k6jo7jzpnJMLRp9P6YOaJ8U5/DDQOGC2GprbqkCIAkL9NOB2bb8E2D4eYDLB7FWhBjWKbRRx7JmPW+9x6viJ5Y=
  file:
    - electrum-dash/dist/Electrum-DASH-2.6.4.tar.gz
    - electrum-dash/dist/electrum-setup.exe
  on:
    repo: akhavr/electrum-dash-release
    all_branches: true